
(load "utils")
(load "structures")

(defun create-if (lst)
	(if (> (list-length lst) 1)
		(let ((attr (nth 0 lst))
			 (condition (nth 1 lst))			
			 (val-to-check (nth 2 lst))
			 (result-val (nth 3 lst))
			 (else-val (cddddr lst))			 
			 )
			 (if (atom result-val)			 
				`(if (,condition ,attr ,val-to-check) ,result-val ,(create-if (cons attr else-val) ) )
				(let ((x (create-if result-val )))
					`(if (,condition ,attr ,val-to-check) ,x ,(create-if (cons attr else-val) ) )					
				)
			)
		)
	)
)

(defmacro create-ifm (lst)
	(create-if lst)
)

(defun str-concat (a b ) (string-upcase (concatenate 'string a b)))
(defun append-to-symbol (sy appendix) (str-concat (string sy) appendix))
(defun create-new-symbol (sy appendix) (
	slet (combined (append-to-symbol sy appendix))
	(slet  ( cb (intern combined) )
		`(,@cb)
	)))


(defun prefix-of (s)  (subseq (string s) 0 1))
(defun attr-name-of (s)  (subseq (string s) 2))

;; p.age -> (person-age p)
(defun map-parameter (formula-parameter) 
	(slet (firstchar (prefix-of formula-parameter))
		(if (string-equal firstchar "P" )
			(slet (varname (attr-name-of formula-parameter) )
				(slet (f-name (find-symbol (str-concat "person-" varname)))
					`(,f-name p)				
				)))))

(defmacro deformula (func-name pars expr)
	(slet (combined (append-to-symbol func-name "wrapper"))
        (slet  ( cb (intern combined) )
			(slet (wrapper-pars (mapcar #'map-parameter pars) ) 
        	`(progn				
				(defun ,func-name ,pars  (create-ifm ,expr) )
				(defun ,cb  (p) (,func-name ,@wrapper-pars)  )
				)
            ))))